#ifndef __AUTOCONF_H__
#define __AUTOCONF_H__
/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Linux/x86 3.12.0 Kernel Configuration
 *
 */
#define CONFIG_RING_BUFFER 1

#define CONFIG_NEED_PER_CPU_EMBED_FIRST_CHUNK 1

#define CONFIG_X86_TSC 1

#define CONFIG_INLINE_WRITE_UNLOCK_IRQ 1
#define CONFIG_HIBERNATION 1

#define CONFIG_HAVE_MEMORY_PRESENT 1

#define CONFIG_COMPAT 1

#define CONFIG_HOTPLUG_CPU 1

#define CONFIG_IA32_EMULATION 1

#define CONFIG_NEED_PER_CPU_PAGE_FIRST_CHUNK 1
#define CONFIG_MODULES_USE_ELF_RELA 1

#define CONFIG_USE_PERCPU_NUMA_NODE_ID 1

#define CONFIG_PRINTK 1

#define CONFIG_TRACEPOINTS 1

#define CONFIG_ENABLE_MUST_CHECK 1

#define CONFIG_X86 1

#define CONFIG_ARCH_CLOCKSOURCE_DATA 1

#define CONFIG_ARCH_USE_BUILTIN_BSWAP 1

#define CONFIG_ACPI 1

#define CONFIG_MTRR 1

#define CONFIG_ARCH_SUPPORTS_OPTIMIZED_INLINING 1

#define CONFIG_X86_MPPARSE 1

#define CONFIG_SCHED_MC 1

#define CONFIG_EFI 1

#define CONFIG_HAVE_SETUP_PER_CPU_AREA 1

#define CONFIG_PROVIDE_OHCI1394_DMA_INIT 1
#define CONFIG_BUG 1

#define CONFIG_PM 1

#define CONFIG_ZONE_DMA 1

#define CONFIG_X86_64_SMP 1

#define CONFIG_SPARSEMEM_EXTREME 1

#define CONFIG_EVENT_TRACING 1

#define CONFIG_PREEMPT_VOLUNTARY 1

#define CONFIG_X86_CMOV 1

#define CONFIG_DEBUG_BUGVERBOSE 1

#define CONFIG_X86_INTERNODE_CACHE_SHIFT 6

#define CONFIG_DEBUG_DEVRES 1

#define CONFIG_TRACE_IRQFLAGS_SUPPORT 1

#define CONFIG_TREE_RCU 1

#define CONFIG_HAVE_KVM 1

#define CONFIG_TIMER_STATS 1

#define CONFIG_HUGETLB_PAGE 1

#define CONFIG_MODULES 1

#define CONFIG_HAVE_MEMBLOCK_NODE_MAP 1

#define CONFIG_KPROBES 1

#define CONFIG_PM_SLEEP 1

#define CONFIG_GENERIC_FIND_FIRST_BIT 1

#define CONFIG_KALLSYMS 1
#define CONFIG_PCI 1

#define CONFIG_NUMA 1

#define CONFIG_ACPI_SLEEP 1

#define CONFIG_NODES_SHIFT 6

#define CONFIG_FREEZER 1

#define CONFIG_X86_DEBUGCTLMSR 1

#define CONFIG_X86_LOCAL_APIC 1

#define CONFIG_X86_DEV_DMA_OPS 1

#define CONFIG_USE_GENERIC_SMP_HELPERS 1

#define CONFIG_ILLEGAL_POINTER_VALUE 0xdead000000000000
#define CONFIG_ILLEGAL_POINTER_VALUEUL 0xdead000000000000

#define CONFIG_SMP 1

#define CONFIG_GENERIC_BUG 1

#define CONFIG_UID16 1

#define CONFIG_INLINE_READ_UNLOCK 1

#define CONFIG_VT_CONSOLE_SLEEP 1

#define CONFIG_X86_64 1

#define CONFIG_DEBUG_STACK_USAGE 1
#define CONFIG_ARCH_HAS_CACHE_LINE_SIZE 1

#define CONFIG_SPARSEMEM_VMEMMAP 1

#define CONFIG_OPTIMIZE_INLINING 1

#define CONFIG_CLOCKSOURCE_WATCHDOG 1

#define CONFIG_INLINE_READ_UNLOCK_IRQ 1

#define CONFIG_SPARSEMEM 1

#define CONFIG_SCHED_SMT 1

#define CONFIG_X86_IO_APIC 1

#define CONFIG_HAS_IOPORT 1

#define CONFIG_X86_CMPXCHG64 1

#define CONFIG_HZ 1000

#define CONFIG_NEED_MULTIPLE_NODES 1

#define CONFIG_INLINE_SPIN_UNLOCK_IRQ 1

#define CONFIG_NR_CPUS 64

#define CONFIG_SYSFS 1

#define CONFIG_TRACING 1

#define CONFIG_AMD_IOMMU 1

#define CONFIG_MUTEX_SPIN_ON_OWNER 1

#define CONFIG_EARLY_PRINTK 1

#define CONFIG_COMPACTION 1

#define CONFIG_PROC_FS 1

#define CONFIG_GENERIC_BUG_RELATIVE_POINTERS 1

#define CONFIG_SYSCTL 1
#define CONFIG_PHYS_ADDR_T_64BIT 1

#define CONFIG_NO_BOOTMEM 1

#define CONFIG_INTEL_IOMMU 1

#define CONFIG_ACPI_NUMA 1

#define CONFIG_ZONE_DMA32 1

#define CONFIG_BINARY_PRINTF 1

#define CONFIG_64BIT 1

#define CONFIG_NODES_SPAN_OTHER_NODES 1

#define CONFIG_MODULE_UNLOAD 1

#define CONFIG_X86_L1_CACHE_SHIFT 6

#define CONFIG_ARCH_DMA_ADDR_T_64BIT 1

#define CONFIG_MMU 1

#define CONFIG_INLINE_WRITE_UNLOCK 1

#endif /* ! __AUTOCONF_H__ */
